# -*- coding: utf-8 -*-
"""anarghya bf47 lab2 8puzzle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leheOIMoFmQwgKCX_944ZXI6RE04o4YK
"""

# Move order: UP, DOWN, LEFT, RIGHT
    moves = [
        (-1, 0, "UP"),
        (1, 0, "DOWN"),
        (0, -1, "LEFT"),
        (0, 1, "RIGHT")
    ]

    for dr, dc, move in moves:

        new_row = row + dr
        new_col = col + dc

        # Check whether move is valid
        if 0 <= new_row < 3 and 0 <= new_col < 3:

            new_zero = new_row * 3 + new_col

            # Create new state
            new_state = state.copy()

            # Swap blank with the tile
            new_state[zero], new_state[new_zero] = \
                new_state[new_zero], new_state[zero]

            # Avoid already visited states
            if tuple(new_state) not in visited:

                result = dfs(
                    new_state,
                    goal,
                    path + [move],
                    visited
                )

                # If solution found, return it
                if result is not None:
                    return result

    return None


# Initial state
initial = [
    2, 8, 3,
    1, 6, 4,
    7, 0, 5
]

# Goal state
goal = [
    1, 2, 3,
    8, 0, 4,
    7, 6, 5
]

# Run DFS
solution = dfs(initial, goal, [], set())

if solution:
    print("Solution found!")
    print("Moves:", solution)
    print("Number of moves:", len(solution))
else:
    print("No solution found.")

def dfs(state, goal, path, visited):
    # Find the index of the blank tile (0)
    zero = state.index(0)
    row, col = zero // 3, zero % 3

    # Check if the goal state is reached
    if state == goal:
        return path

    # Mark the current state as visited
    visited.add(tuple(state))

    # Move order: UP, DOWN, LEFT, RIGHT
    moves = [(-1, 0, "UP"), (1, 0, "DOWN"), (0, -1, "LEFT"), (0, 1, "RIGHT")]

    for dr, dc, move in moves:
        new_row = row + dr
        new_col = col + dc

        # Check whether move is valid
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_zero = new_row * 3 + new_col

            # Create new state
            new_state = state.copy()

            # Swap blank with the tile
            new_state[zero], new_state[new_zero] = new_state[new_zero], new_state[zero]

            # Avoid already visited states
            if tuple(new_state) not in visited:
                result = dfs(new_state, goal, path + [move], visited)

                # If solution found, return it
                if result is not None:
                    return result

    # Backtrack: remove from visited if this path completely fails
    visited.remove(tuple(state))
    return None

# Initial state
initial = [2, 8, 3, 1, 6, 4, 7, 0, 5]
# Goal state
goal = [1, 2, 3, 8, 0, 4, 7, 6, 5]

# Run DFS
solution = dfs(initial, goal, [], set())

if solution:
    print("Solution found!")
    print("Moves:", solution)
    print("Number of moves:", len(solution))
else:
    print("No solution found.")

def print_state(state):
    for i in range(0, 9, 3):
        print(state[i], state[i + 1], state[i + 2])
    print()


def depth_limited_search(state, goal, depth, path, on_path):
    # Goal test
    if state == goal:
        return path

    # Depth limit reached
    if depth == 0:
        return None

    state_tuple = tuple(state)
    on_path.add(state_tuple)

    # Position of blank (0)
    zero = state.index(0)
    row = zero // 3
    col = zero % 3

    # Order in which moves are tried
    moves = [
        (-1, 0, "UP"),
        (1, 0, "DOWN"),
        (0, -1, "LEFT"),
        (0, 1, "RIGHT")
    ]

    for dr, dc, move in moves:

        new_row = row + dr
        new_col = col + dc

        # Check whether move is inside the board
        if 0 <= new_row < 3 and 0 <= new_col < 3:

            new_zero = new_row * 3 + new_col

            # Create new state
            new_state = state.copy()

            # Swap blank with adjacent tile
            new_state[zero], new_state[new_zero] = \
                new_state[new_zero], new_state[zero]

            new_state_tuple = tuple(new_state)

            # Avoid cycles in current path
            if new_state_tuple not in on_path:

                result = depth_limited_search(
                    new_state,
                    goal,
                    depth - 1,
                    path + [(move, new_state.copy())],
                    on_path
                )

                if result is not None:
                    return result

    # Backtrack
    on_path.remove(state_tuple)

    return None


def IDS(initial, goal):

    depth = 0

    while True:

        print("================================")
        print("Searching at depth:", depth)
        print("================================")

        result = depth_limited_search(
            initial,
            goal,
            depth,
            [],
            set()
        )

        if result is not None:
            return result

        depth += 1


# -------------------------------
# MAIN PROGRAM
# -------------------------------

initial = [
    2, 8, 3,
    1, 6, 4,
    7, 0, 5
]

goal = [
    1, 2, 3,
    8, 0, 4,
    7, 6, 5
]


print("INITIAL STATE:")
print_state(initial)

print("GOAL STATE:")
print_state(goal)


solution = IDS(initial, goal)


print("================================")
print("SOLUTION")
print("================================")

print("Initial State:")
print_state(initial)


for move, state in solution:
    print("Move:", move)
    print_state(state)


print("Goal Reached!")
print("Number of moves:", len(solution))